[package]
name = "poser"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["macros"] }
base64 = "0.21"
bytes = "1.0"
ct-codecs = "1.1"
ed25519 = "2.2"
ed25519-compact = "2.0"
openidconnect = "2.5"
pasetors = "0.6"
pkcs8 = "0.10"
ring = "0.16"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signature = "2.0"
thiserror = "1.0"
time = { version = "0.3", features = ["formatting", "parsing"] }
tokio = { version = "1.25", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-time-0_3", "with-uuid-1"] }
tower = "0.4"
tower-cookies = "0.9"
tower-http = { version = "0.3", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.3", features = ["v4", "fast-rng"] }

# the current pre-release doesn't compile, so I'm using git for now
[dependencies.ed25519-dalek]
git = "https://github.com/dalek-cryptography/ed25519-dalek.git"
features = ["pem"]

[dev-dependencies]
hex-literal = "0.3"
